# Non_interactive containers (9)
- '$surface_primary_backgroundColor'
- '$surface_primary_foregroundColor'
- '$surface_primary_borderColor'
- '$surface_secondary_backgroundColor'
- '$surface_secondary_foregroundColor'
- '$surface_secondary_borderColor'
- '$surface_auxiliary_backgroundColor'
- '$surface_auxiliary_foregroundColor'
- '$surface_auxiliary_borderColor'

# Buttons and links (9)
- '$action_primary_backgroundColor'
- '$action_primary_foregroundColor'
- '$action_primary_borderColor'
- '$action_secondary_backgroundColor'
- '$action_secondary_foregroundColor'
- '$action_secondary_borderColor'
- '$action_auxiliary_backgroundColor'
- '$action_auxiliary_foregroundColor'
- '$action_auxiliary_borderColor'

# Form controls (3)
- '$control_backgroundColor'
- '$control_foregroundColor'
- '$control_borderColor'

# Font metrics (12)
- '$text_primary_fontFamily'
- '$text_primary_fontWeight'
- '$text_primary_fontSize'
- '$text_primary_lineHeight'
- '$text_secondary_fontFamily'
- '$text_secondary_fontWeight'
- '$text_secondary_fontSize'
- '$text_secondary_lineHeight'
- '$text_secondary_scaleFactor'
- '$text_auxiliary_fontFamily'
- '$text_auxiliary_fontWeight'
- '$text_auxiliary_fontSize'
- '$text_auxiliary_lineHeight'
